### PR TITLE
Updates to the installation documentation

### PR DESCRIPTION
**Pull request by GlynnPhillips**
I followed the original documention to set up the webapp and found it
slightlty confusing and that slightly too much prior knowledge was
required.

Hopefully this will make getting the webapp up and running slightly
easier for some people.

### CODE REVIEW

**Comment by GlynnPhillips** [comment]
I signed it!

**Comment by darrentorpey** [comment]
This was helpful for me. Thanks, @GlynnPhillips

**Comment by andrewmee** [comment]
Much clearer - much less prior knowledge required :+1:

**Comment by paullewis** [comment]
@GlynnPhillips LGTM - thanks ever so much for taking time to contribute! :fireworks:

**Pull request merged**
